#!/usr/bin/env sh
set -eu

ROOT="${1:-.}"
cd "$ROOT"

fail() {
  printf '%s\n' "FAIL: $*" >&2
  exit 1
}

require_file() {
  [ -f "$1" ] || fail "missing required file: $1"
}

require_grep() {
  pattern="$1"
  file="$2"
  grep -Eq "$pattern" "$file" || fail "missing pattern in $file: $pattern"
}

SKILL_DIR=".agents/skills/quant-candidate-ml-gate"
SKILL_FILE="$SKILL_DIR/SKILL.md"
SCRIPT_FILE="$SKILL_DIR/scripts/validate_gate_contract.sh"
META_FILE="$SKILL_DIR/agents/openai.yaml"
SCORE_CONTRACT="Quant_mvp/docs/v0_2_candidate_ml_score_contract.md"
GATE1_DOC="Quant_mvp/docs/v0_2_candidate_ml_implementation_gate_1.md"
GATE1_CONFIG="Quant_mvp/config/v0_2_candidate_ml_score.toml"
BACKTEST_APPROVAL_PACKET="Quant_mvp/docs/v0_2_candidate_ml_evaluation_backtest_approval_packet.md"
PRODUCTION_ACTIVATION_PACKET="Quant_mvp/docs/v0_2_candidate_ml_production_activation_root_approval_packet.md"

require_file "AGENTS.md"
require_file "docs/root_hard_stops.md"
require_file "docs/roadmap_status.md"
require_file "$SKILL_FILE"
require_file "$SCRIPT_FILE"
require_file "$META_FILE"
require_file "$SCORE_CONTRACT"
require_file "$GATE1_DOC"
require_file "$GATE1_CONFIG"
require_file "$BACKTEST_APPROVAL_PACKET"
require_file "$PRODUCTION_ACTIVATION_PACKET"

rule_count="$(grep -Ec '^[0-9]+\.' AGENTS.md)"
[ "$rule_count" -eq 11 ] || fail "AGENTS.md must contain exactly 11 numbered router rules; found $rule_count"

require_grep 'root_hard_stops\.md' "AGENTS.md"
require_grep 'roadmap_status\.md' "AGENTS.md"
require_grep '\.agents/skills/quant-candidate-ml-gate/SKILL\.md' "AGENTS.md"
require_grep '\.agents/skills/quant-review-gate/SKILL\.md' "AGENTS.md"
require_grep 'user prompt.*local goal|gate.*local goal|goal/output' "AGENTS.md"

require_grep 'current project authority|project authority' "docs/root_hard_stops.md"
require_grep 'prob_up_1d_candidate' "docs/root_hard_stops.md"
require_grep 'candidate-only|candidate ML|candidate probability' "docs/root_hard_stops.md"
require_grep '\.agents/skills/quant-candidate-ml-gate/SKILL\.md' "docs/root_hard_stops.md"
require_grep 'technical_composite_score' "docs/root_hard_stops.md"
require_grep 'final_composite_score' "docs/root_hard_stops.md"
require_grep 'Trading recommendations|trading recommendations|b[u]y/s[e]ll/h[o]ld' "docs/root_hard_stops.md"

require_grep 'v0\.2 predictive probability score route' "docs/roadmap_status.md"
require_grep 'prob_up_1d_candidate' "docs/roadmap_status.md"
require_grep '\.agents/skills/quant-candidate-ml-gate/SKILL\.md' "docs/roadmap_status.md"

require_grep '^name: quant-candidate-ml-gate$' "$SKILL_FILE"
require_grep '^description: .*prob_up_1d_candidate' "$SKILL_FILE"
require_grep 'Do Not Use When' "$SKILL_FILE"
require_grep 'prob_up_1d_candidate' "$SKILL_FILE"
require_grep 'candidate-only|candidate_only' "$SKILL_FILE"
require_grep 'label-separated' "$SKILL_FILE"
require_grep 'validate_gate_contract\.sh' "$SKILL_FILE"
require_grep 'display_name: "Quant Candidate ML Gate"' "$META_FILE"

require_grep 'Gate 1 Availability Preconditions' "$SCORE_CONTRACT"
require_grep 'CONFIRMED_EXISTING_OPTIONAL_ALIAS_ADJ_CLOSE' "$SCORE_CONTRACT"
require_grep 'adj_close.*only approved alias|only approved alias.*adj_close' "$SCORE_CONTRACT"
require_grep 'adjusted_close\[t\+1\] > adjusted_close\[t\]' "$SCORE_CONTRACT"
require_grep 'decision_time' "$SCORE_CONTRACT"
require_grep 'execution_time' "$SCORE_CONTRACT"
require_grep 'label_time' "$SCORE_CONTRACT"
require_grep 'label_availability_time' "$SCORE_CONTRACT"
require_grep 'default-deny|default deny' "$SCORE_CONTRACT"
require_grep 'build_prob_up_1d_feature_input_frame' "$SCORE_CONTRACT"
require_grep 'step9_raw_technical_old_scores' "$SCORE_CONTRACT"
require_grep 'old_score_feature_columns' "$SCORE_CONTRACT"
require_grep 'Walk-Forward Evaluation Boundary' "$SCORE_CONTRACT"
require_grep 'evaluate_prob_up_1d_candidate_walk_forward' "$SCORE_CONTRACT"
require_grep 'time-ordered expanding-window|time_ordered_expanding_window' "$SCORE_CONTRACT"
require_grep 'brier_score' "$SCORE_CONTRACT"
require_grep 'log_loss' "$SCORE_CONTRACT"
require_grep 'calibration_error' "$SCORE_CONTRACT"
require_grep 'feature_stability_mean_abs_shift' "$SCORE_CONTRACT"
require_grep 'sidecar_candidate_only' "$SCORE_CONTRACT"
require_grep 'Selection Packet Boundary' "$SCORE_CONTRACT"
require_grep 'build_prob_up_1d_candidate_selection_packet' "$SCORE_CONTRACT"
require_grep 'prob_up_1d_candidate desc, ticker asc' "$SCORE_CONTRACT"
require_grep 'candidate_sidecar/selection_packet' "$SCORE_CONTRACT"
require_grep 'Evaluation-Only Backtest Approval Boundary' "$SCORE_CONTRACT"
require_grep 'v0_2_candidate_ml_evaluation_backtest_approval_packet\.md' "$SCORE_CONTRACT"
require_grep 'Production Activation Root Approval Boundary' "$SCORE_CONTRACT"
require_grep 'v0_2_candidate_ml_production_activation_root_approval_packet\.md' "$SCORE_CONTRACT"

require_grep 'adjusted_close.*Availability Contract' "$GATE1_DOC"
require_grep 'CONFIRMED_EXISTING_OPTIONAL_ALIAS_ADJ_CLOSE' "$GATE1_DOC"
require_grep 'Approved alias list: `adj_close` only' "$GATE1_DOC"
require_grep 'Feature Allowlist Contract' "$GATE1_DOC"
require_grep 'build_prob_up_1d_feature_input_frame' "$GATE1_DOC"
require_grep 'step9_raw_technical_old_scores' "$GATE1_DOC"
require_grep 'old_score_feature_columns' "$GATE1_DOC"
require_grep 'Walk-Forward Evaluation Contract' "$GATE1_DOC"
require_grep 'evaluate_prob_up_1d_candidate_walk_forward' "$GATE1_DOC"
require_grep 'export_prob_up_1d_walk_forward_evaluation' "$GATE1_DOC"
require_grep 'time_ordered_expanding_window' "$GATE1_DOC"
require_grep 'prob_up_1d_candidate_walk_forward_metric_summary_\{as_of_date\}\.csv' "$GATE1_DOC"
require_grep 'Explicit Feature Exclusions' "$GATE1_DOC"
require_grep 'Timing Field Definitions' "$GATE1_DOC"
require_grep 'No-Lookahead Validation And Test Contract' "$GATE1_DOC"
require_grep 'Sidecar Candidate Output Path Contract' "$GATE1_DOC"
require_grep 'prob_up_1d_candidate_candidate_only_sidecar_\{as_of_date\}\.csv' "$GATE1_DOC"
require_grep 'prob_up_1d_candidate.*descending' "$GATE1_DOC"
require_grep 'ticker.*ascending' "$GATE1_DOC"
require_grep 'up_1d_label = adjusted_close\[t\+1\] > adjusted_close\[t\]' "$GATE1_DOC"
require_grep 'Sidecar Selection Packet Contract' "$GATE1_DOC"
require_grep 'build_prob_up_1d_candidate_selection_packet' "$GATE1_DOC"
require_grep 'export_prob_up_1d_candidate_selection_packet' "$GATE1_DOC"
require_grep 'prob_up_1d_candidate_selection_packet_\{as_of_date\}\.csv' "$GATE1_DOC"
require_grep 'prob_up_1d_candidate.*descending' "$GATE1_DOC"
require_grep 'ticker.*ascending' "$GATE1_DOC"
require_grep 'Evaluation-Only Backtest Approval Packet' "$GATE1_DOC"
require_grep 'v0_2_candidate_ml_evaluation_backtest_approval_packet\.md' "$GATE1_DOC"
require_grep 'Production Activation Root Approval Packet' "$GATE1_DOC"
require_grep 'v0_2_candidate_ml_production_activation_root_approval_packet\.md' "$GATE1_DOC"

require_grep '\[adjusted_close_source\]' "$GATE1_CONFIG"
require_grep 'repo_availability_status = "CONFIRMED_EXISTING_OPTIONAL_ALIAS_ADJ_CLOSE"' "$GATE1_CONFIG"
require_grep 'approved_aliases = \["adj_close"\]' "$GATE1_CONFIG"
require_grep 'close_alias_status = "not_approved"' "$GATE1_CONFIG"
require_grep 'allow_close_fallback = false' "$GATE1_CONFIG"
require_grep 'allow_new_market_data_ingestion = false' "$GATE1_CONFIG"
require_grep '\[feature_allowlist\]' "$GATE1_CONFIG"
require_grep 'mode = "default_deny"' "$GATE1_CONFIG"
require_grep 'feature_input_path = "src\.scores\.prob_up_1d_candidate\.build_prob_up_1d_feature_input_frame"' "$GATE1_CONFIG"
require_grep 'feature_source = "step9_raw_technical_old_scores"' "$GATE1_CONFIG"
require_grep 'schema_consistency_validator = "src\.scores\.prob_up_1d_candidate\.validate_prob_up_1d_schema_consistency"' "$GATE1_CONFIG"
require_grep 'old_score_feature_columns = \[' "$GATE1_CONFIG"
require_grep '"short_term_overreaction_raw"' "$GATE1_CONFIG"
require_grep '"atr_adjusted_oversold_distance_raw"' "$GATE1_CONFIG"
require_grep '"rsi_price_divergence_raw"' "$GATE1_CONFIG"
require_grep '"realized_vol_percentile_raw"' "$GATE1_CONFIG"
require_grep '"donchian_breakout_distance_raw"' "$GATE1_CONFIG"
require_grep '"bollinger_width_squeeze_raw"' "$GATE1_CONFIG"
require_grep '"cmf_confirmation_raw"' "$GATE1_CONFIG"
require_grep '"efficiency_ratio_trend_raw"' "$GATE1_CONFIG"
require_grep '\[missing_data_policy\]' "$GATE1_CONFIG"
require_grep 'feature_status_field = "prob_up_1d_feature_status"' "$GATE1_CONFIG"
require_grep 'feature_valid_count_field = "prob_up_1d_feature_valid_count"' "$GATE1_CONFIG"
require_grep 'train_eval_requires_complete_features = true' "$GATE1_CONFIG"
require_grep '\[walk_forward_evaluation\]' "$GATE1_CONFIG"
require_grep 'implementation_path = "src\.scores\.prob_up_1d_candidate\.evaluate_prob_up_1d_candidate_walk_forward"' "$GATE1_CONFIG"
require_grep 'export_path = "src\.scores\.prob_up_1d_candidate\.export_prob_up_1d_walk_forward_evaluation"' "$GATE1_CONFIG"
require_grep 'split_mode = "time_ordered_expanding_window"' "$GATE1_CONFIG"
require_grep 'random_split_primary = false' "$GATE1_CONFIG"
require_grep 'candidate_only_diagnostic = true' "$GATE1_CONFIG"
require_grep 'feeds_model_selection_from_return_performance = false' "$GATE1_CONFIG"
require_grep 'brier_score' "$GATE1_CONFIG"
require_grep 'log_loss' "$GATE1_CONFIG"
require_grep 'calibration_error' "$GATE1_CONFIG"
require_grep 'nan_missing_rate' "$GATE1_CONFIG"
require_grep 'feature_stability_mean_abs_shift' "$GATE1_CONFIG"
require_grep '\[walk_forward_evaluation_output_path\]' "$GATE1_CONFIG"
require_grep 'root = "reports/v0_2_predictive_probability/evaluation"' "$GATE1_CONFIG"
require_grep '\[no_lookahead_validation\]' "$GATE1_CONFIG"
require_grep 'feature_time_must_be_lte_decision_time = true' "$GATE1_CONFIG"
require_grep 'label_availability_must_be_after_decision_time = true' "$GATE1_CONFIG"
require_grep '\[sidecar_output_path\]' "$GATE1_CONFIG"
require_grep 'generation_implemented_in_gate_1 = false' "$GATE1_CONFIG"
require_grep 'feeds_production_ranking = false' "$GATE1_CONFIG"
require_grep 'feeds_reports = false' "$GATE1_CONFIG"
require_grep 'feeds_composite_scores = false' "$GATE1_CONFIG"
require_grep 'replace_technical_composite_score = false' "$GATE1_CONFIG"
require_grep 'replace_final_composite_score = false' "$GATE1_CONFIG"
require_grep '\[sidecar_selection_packet\]' "$GATE1_CONFIG"
require_grep 'packet_type = "candidate_sidecar_selection_packet"' "$GATE1_CONFIG"
require_grep 'implementation_path = "src\.scores\.prob_up_1d_candidate\.build_prob_up_1d_candidate_selection_packet"' "$GATE1_CONFIG"
require_grep 'export_path = "src\.scores\.prob_up_1d_candidate\.export_prob_up_1d_candidate_selection_packet"' "$GATE1_CONFIG"
require_grep 'schema_validator = "src\.scores\.prob_up_1d_candidate\.validate_prob_up_1d_selection_packet_schema"' "$GATE1_CONFIG"
require_grep 'sort_fields = \["prob_up_1d_candidate", "ticker"\]' "$GATE1_CONFIG"
require_grep 'sort_directions = \["desc", "asc"\]' "$GATE1_CONFIG"
require_grep 'allow_production_rank_field = false' "$GATE1_CONFIG"
require_grep 'allow_sidecar_rank_field = false' "$GATE1_CONFIG"
require_grep '\[sidecar_selection_packet_output_path\]' "$GATE1_CONFIG"
require_grep 'root = "reports/v0_2_predictive_probability/candidate_sidecar/selection_packet"' "$GATE1_CONFIG"
require_grep 'filename_template = "prob_up_1d_candidate_selection_packet_\{as_of_date\}\.csv"' "$GATE1_CONFIG"
require_grep '\[evaluation_only_backtest_approval\]' "$GATE1_CONFIG"
require_grep 'status = "root_approved_evaluation_only_diagnostic_implemented"' "$GATE1_CONFIG"
require_grep 'approval_packet_path = "Quant_mvp/docs/v0_2_candidate_ml_evaluation_backtest_approval_packet\.md"' "$GATE1_CONFIG"
require_grep 'implementation_path = "src\.scores\.prob_up_1d_candidate\.run_prob_up_1d_evaluation_only_backtest"' "$GATE1_CONFIG"
require_grep 'loader_path = "src\.scores\.prob_up_1d_candidate\.load_candidate_probability_artifact"' "$GATE1_CONFIG"
require_grep 'export_path = "src\.scores\.prob_up_1d_candidate\.export_prob_up_1d_evaluation_only_backtest"' "$GATE1_CONFIG"
require_grep 'implementation_authorized = true' "$GATE1_CONFIG"
require_grep 'root_approval_received = true' "$GATE1_CONFIG"
require_grep 'root_approval_required = true' "$GATE1_CONFIG"
require_grep 'candidate_artifact_allowed_as_evaluation_input = true' "$GATE1_CONFIG"
require_grep 'candidate_artifact_allowed_as_feature_input = false' "$GATE1_CONFIG"
require_grep 'candidate_artifact_allowed_as_model_selection_input = false' "$GATE1_CONFIG"
require_grep 'backtest_feedback_into_model = false' "$GATE1_CONFIG"
require_grep 'backtest_feedback_into_reports = false' "$GATE1_CONFIG"
require_grep 'model_selection_from_backtest = false' "$GATE1_CONFIG"
require_grep 'feature_selection_from_backtest = false' "$GATE1_CONFIG"
require_grep 'cutoff_selection_from_backtest = false' "$GATE1_CONFIG"
require_grep '\[evaluation_only_backtest\]' "$GATE1_CONFIG"
require_grep 'status = "candidate_only_diagnostic_implemented"' "$GATE1_CONFIG"
require_grep 'artifact_type = "candidate_only_evaluation_backtest_diagnostic"' "$GATE1_CONFIG"
require_grep 'rejects_feedback_config_updates = true' "$GATE1_CONFIG"
require_grep 'writes_diagnostics_only = true' "$GATE1_CONFIG"
require_grep '\[production_activation_root_approval\]' "$GATE1_CONFIG"
require_grep 'status = "root_approval_review_packet_only_not_activated"' "$GATE1_CONFIG"
require_grep 'approval_packet_path = "Quant_mvp/docs/v0_2_candidate_ml_production_activation_root_approval_packet\.md"' "$GATE1_CONFIG"
require_grep 'activation_decision_state = "approval_review_ready_not_decided"' "$GATE1_CONFIG"
require_grep 'activation_executed = false' "$GATE1_CONFIG"
require_grep 'candidate_only_state_preserved = true' "$GATE1_CONFIG"
require_grep 'evaluation_only_backtest_approved = true' "$GATE1_CONFIG"
require_grep 'evaluation_only_backtest_implemented = true' "$GATE1_CONFIG"
require_grep 'score_runtime_semantics_gate' "$GATE1_CONFIG"
require_grep 'disable_plan_review' "$GATE1_CONFIG"
require_grep 'rollback_rehearsal_evidence_missing' "$GATE1_CONFIG"

require_grep '^# v0\.2 Candidate ML Evaluation-Only Backtest Approval Packet' "$BACKTEST_APPROVAL_PACKET"
require_grep 'Status: root approved for evaluation-only diagnostic implementation' "$BACKTEST_APPROVAL_PACKET"
require_grep 'Root approval has been received for this evaluation-only diagnostic connection' "$BACKTEST_APPROVAL_PACKET"
require_grep 'Root Approval Requirement' "$BACKTEST_APPROVAL_PACKET"
require_grep 'Required Validators Before Implementation' "$BACKTEST_APPROVAL_PACKET"
require_grep 'Forbidden Feedback Loop Test Plan' "$BACKTEST_APPROVAL_PACKET"
require_grep 'backtest_feedback_into_features = false' "$BACKTEST_APPROVAL_PACKET"
require_grep 'backtest_feedback_into_model = false' "$BACKTEST_APPROVAL_PACKET"
require_grep 'model_selection_from_backtest = false' "$BACKTEST_APPROVAL_PACKET"
require_grep 'cutoff_selection_from_backtest = false' "$BACKTEST_APPROVAL_PACKET"

require_grep '^# v0\.2 Candidate ML Production Activation Root Approval Packet' "$PRODUCTION_ACTIVATION_PACKET"
require_grep 'Status: root approval review packet only' "$PRODUCTION_ACTIVATION_PACKET"
require_grep 'approval_review_ready_not_decided' "$PRODUCTION_ACTIVATION_PACKET"
require_grep 'activation executed: false' "$PRODUCTION_ACTIVATION_PACKET"
require_grep 'root approval required before any runtime behavior changes: true' "$PRODUCTION_ACTIVATION_PACKET"
require_grep 'Current Candidate-Only Output Summary' "$PRODUCTION_ACTIVATION_PACKET"
require_grep 'Model Evaluation Summary' "$PRODUCTION_ACTIVATION_PACKET"
require_grep 'Leakage And No-Lookahead Audit Summary' "$PRODUCTION_ACTIVATION_PACKET"
require_grep 'Adjusted Close Canonical Source' "$PRODUCTION_ACTIVATION_PACKET"
require_grep 'Sidecar Packet Validation Summary' "$PRODUCTION_ACTIVATION_PACKET"
require_grep 'Evaluation-Only Backtest Approval State' "$PRODUCTION_ACTIVATION_PACKET"
require_grep 'Additional Gates Required Before Production Activation' "$PRODUCTION_ACTIVATION_PACKET"
require_grep 'Rollback And Disable Plan Draft' "$PRODUCTION_ACTIVATION_PACKET"
require_grep 'Next Root Decision Items' "$PRODUCTION_ACTIVATION_PACKET"
require_grep 'approved for diagnostic-only implementation' "$PRODUCTION_ACTIVATION_PACKET"
require_grep 'diagnostics are generated for the exact candidate artifact' "$PRODUCTION_ACTIVATION_PACKET"

for pattern in label target future forward_return next_day_return realized_return backtest evaluation generated_report report_output ranking_output candidate_sidecar technical_composite_score final_composite_score; do
  require_grep "\"$pattern\"" "$GATE1_CONFIG"
done

trade_word_pattern='b[u]y|s[e]ll|h[o]ld|매[수]|매[도]|보[유]|expected[ -]return|proven[ -]alpha|profitability[ -]proof|superior[ -]strategy'
if grep -Eiq "$trade_word_pattern" "$SCORE_CONTRACT" "$GATE1_DOC" "$GATE1_CONFIG" "$SKILL_FILE" "$BACKTEST_APPROVAL_PACKET" "$PRODUCTION_ACTIVATION_PACKET"; then
  fail "direct trading or performance-claim wording found in gate docs/config/skill"
fi

printf '%s\n' "PASS: quant candidate ML gate contract is present"
